"use client";

import { useEffect, useRef, useCallback, forwardRef, useImperativeHandle } from "react";
import type { CSSProperties } from "react";

/**
 * Result structure from agent operations via the personal server.
 * This is the parsed content from the SDK's GetOperationResponse.result field.
 * @public
 */
export interface AgentOperationResult {
  /** The output from the agent operation - can be a string or JSON object */
  output: unknown;
  /** Optional array of file artifacts generated by the operation */
  artifacts?: {
    /** Name of the artifact file */
    name: string;
    /** Path to the artifact file */
    artifact_path: string;
    /** Size of the artifact in bytes */
    size: number;
    /** MIME type of the artifact */
    content_type?: string;
  }[];
  /** The operation ID for this agent execution - required for downloading artifacts */
  operationId: string;
}

/**
 * Imperative handle exposed via ref for programmatic widget control.
 * Provides methods to interact with the widget after operation completion.
 *
 * Use this handle when your operation generates artifacts (files) that you need to
 * download and process in your application. Agent operations like `prompt_gemini_agent`
 * can produce reports, CSVs, images, or other file outputs that are made available
 * via the artifacts array in the result.
 *
 * @public
 * @example
 * Complete example using ref to download artifacts:
 * ```tsx
 * import { useRef, useState } from 'react';
 * import { VanaAppUploadWidget, VanaAppUploadWidgetHandle, AgentOperationResult } from '@opendatalabs/vana-react';
 *
 * function App() {
 *   const widgetRef = useRef<VanaAppUploadWidgetHandle>(null);
 *   const [downloadedFiles, setDownloadedFiles] = useState<string[]>([]);
 *
 *   const handleResult = async (result: AgentOperationResult) => {
 *     console.log('Operation completed:', result.output);
 *
 *     // Download artifacts if available
 *     if (result.artifacts && result.artifacts.length > 0) {
 *       for (const artifact of result.artifacts) {
 *         try {
 *           // Download artifact using the ref handle
 *           const blob = await widgetRef.current?.downloadArtifact({
 *             operationId: result.operationId,
 *             artifactPath: artifact.artifact_path
 *           });
 *
 *           // Process the downloaded artifact
 *           if (blob) {
 *             // Option 1: Trigger browser download
 *             const url = URL.createObjectURL(blob);
 *             const a = document.createElement('a');
 *             a.href = url;
 *             a.download = artifact.name;
 *             a.click();
 *             URL.revokeObjectURL(url);
 *
 *             // Option 2: Read content for processing
 *             const text = await blob.text();
 *             console.log('Artifact content:', text);
 *
 *             setDownloadedFiles(prev => [...prev, artifact.name]);
 *           }
 *         } catch (error) {
 *           console.error('Failed to download artifact:', error);
 *         }
 *       }
 *     }
 *   };
 *
 *   return (
 *     <div>
 *       <VanaAppUploadWidget
 *         ref={widgetRef}
 *         appId="my-app-123"
 *         operation="prompt_gemini_agent"
 *         operationParams={{ goal: "Generate a comprehensive report" }}
 *         onResult={handleResult}
 *         onError={(error) => console.error('Error:', error)}
 *         onAuth={(wallet) => console.log('Authenticated:', wallet)}
 *       />
 *       {downloadedFiles.length > 0 && (
 *         <div>
 *           <h3>Downloaded artifacts:</h3>
 *           <ul>
 *             {downloadedFiles.map(file => <li key={file}>{file}</li>)}
 *           </ul>
 *         </div>
 *       )}
 *     </div>
 *   );
 * }
 * ```
 */
export interface VanaAppUploadWidgetHandle {
  /**
   * Downloads artifact content from the personal server.
   * @param params - Parameters specifying which artifact to download
   * @param params.operationId - The operation ID that generated the artifact
   * @param params.artifactPath - The artifact path from the AgentOperationResult
   * @returns Promise resolving to the artifact content as a Blob
   * @throws Error if widget is not ready, download fails, or request times out (30s)
   */
  downloadArtifact(params: { operationId: string; artifactPath: string }): Promise<Blob>;
}

/**
 * Theme configuration for customizing the widget's appearance.
 * Uses CSS custom properties for styling.
 * @public
 */
export interface VanaAppUploadTheme {
  /** Background color for the main widget container */
  "--background"?: string;
  /** Background color for card elements */
  "--card"?: string;
  /** Background color for card elements when in dark mode */
  "--card-dark"?: string;
  /** Text color for card elements when in dark mode */
  "--card-foreground-dark"?: string;
  /** Background color for input fields */
  "--input-background"?: string;
  /** Background color for para overlay */
  "--para-overlay-background"?: string;
  /** Primary brand color */
  "--primary"?: string;
  /** Primary foreground (text) color */
  "--primary-foreground"?: string;
  /** Secondary color */
  "--secondary"?: string;
  /** Accent color */
  "--accent"?: string;
  /** Border color */
  "--border"?: string;
  /** Text color */
  "--foreground"?: string;
  /** Muted text color */
  "--muted-foreground"?: string;
  /** Allow any additional CSS custom properties */
  [key: `--${string}`]: string | undefined;
}

/**
 * Configuration properties for the VanaAppUploadWidget component.
 * @public
 */
export interface VanaAppUploadWidgetProps {
  /**
   * Application ID from the Vana Developer Portal (app.vana.com/build).
   * This identifies your app and its associated configuration.
   */
  appId: string;

  /**
   * Callback function invoked when data upload or agent operation completes successfully.
   * @param data - The structured result containing output and optional artifacts
   */
  onResult: (data: AgentOperationResult) => void;

  /**
   * Callback function invoked when an error occurs during the upload process.
   * @param error - Error message describing what went wrong
   */
  onError: (error: string) => void;

  /**
   * Callback function invoked when user successfully authenticates with their wallet.
   * @param walletAddress - The authenticated user's wallet address
   */
  onAuth: (walletAddress: string) => void;

  /**
   * Optional callback function invoked when user closes the widget.
   * Useful for hiding or removing the iframe container.
   */
  onClose?: () => void;

  /**
   * Origin URL of the Vana iframe application.
   * @defaultValue `"https://app.vana.com"`
   */
  iframeOrigin?: string;

  /**
   * Optional schema ID to override the app's default schema.
   * Each app has a configured schema, but you can specify a different one here.
   */
  schemaId?: number;

  /**
   * LLM inference prompt for the user's trusted server.
   * This prompt will be used to process the uploaded data.
   * Kept for backward compatibility - prefer using operation for new implementations.
   * @example
   * "Extract personality insights in JSON format { \"openness\": 0.33 } from user data: {{data}}"
   */
  prompt?: string;

  /**
   * Generic agent operation to execute on the user's personal server.
   *
   * **Important:** This operation is executed on the user's trusted personal server
   * instance (vana-personal-server). The personal server must be running and properly
   * configured to support the requested operation type. The Vana SDK communicates with
   * the user's personal server to execute the operation securely with access to their
   * encrypted data.
   *
   * **Standard supported operations** (vana-personal-server v1.0+):
   * - `llm_inference`: Direct LLM text generation with user data context. Use with
   *   `operationParams: { prompt: string, response_format?: { type: 'json_object' } }`
   * - `prompt_gemini_agent`: Gemini-based agentic task execution with tool use, web
   *   search, and multi-step reasoning. Use with `operationParams: { goal: string }`
   * - `prompt_qwen_agent`: Qwen-based agentic task execution with shell command
   *   capabilities. Use with `operationParams: { goal: string }`
   *
   * Custom operations may also be supported depending on the personal server
   * configuration and installed agent plugins.
   *
   * @example "prompt_gemini_agent"
   * @example "llm_inference"
   */
  operation?: string;

  /**
   * Parameters to pass to the agent operation.
   * These will be sent to the personal server along with the operation.
   * @example { "model": "gpt-4", "temperature": 0.7 }
   */
  operationParams?: Record<string, unknown>;

  /**
   * JSONPath filters to apply to user data before sending to the operation.
   * Maps schema IDs to JSONPath expressions for data filtering.
   * @example { "24": "$.publicData.linkedinUserData.[hero, about.aboutText]" }
   */
  filters?: Record<string, string>;

  /**
   * Custom theme configuration using CSS custom properties.
   * @example
   * ```tsx
   * theme={{
   *   "--primary": "#007bff",
   *   "--background": "transparent",
   *   "--card": "rgba(255, 255, 255, 0.95)",
   *   "--foreground": "#1a1a1a"
   * }}
   * ```
   */
  theme?: VanaAppUploadTheme;

  /**
   * CSS class name(s) to apply to the widget container.
   * @defaultValue `"w-full relative min-h-[550px]"`
   */
  className?: string;

  /**
   * Inline styles to apply to the widget container.
   * Useful for dynamic styling or overriding defaults.
   */
  style?: CSSProperties;
}

/**
 * VanaAppUploadWidget - Embeddable React component for Vana App data upload operations.
 *
 * This component renders an iframe that facilitates secure data upload and processing
 * through the Vana Network. It handles cross-origin communication, wallet authentication,
 * and dynamic resizing.
 *
 * @example
 * Basic usage:
 * ```tsx
 * import { VanaAppUploadWidget } from '@opendatalabs/vana-react';
 *
 * function App() {
 *   return (
 *     <VanaAppUploadWidget
 *       appId="my-app-123"
 *       onResult={(data) => console.log('Upload successful:', data)}
 *       onError={(error) => console.error('Upload failed:', error)}
 *       onAuth={(wallet) => console.log('Authenticated:', wallet)}
 *     />
 *   );
 * }
 * ```
 *
 * @example
 * With custom theme and schema:
 * ```tsx
 * <VanaAppUploadWidget
 *   appId="my-app-123"
 *   schemaId={456}
 *   prompt="Upload your social media data"
 *   theme={{
 *     primaryColor: "#6366f1",
 *     backgroundColor: "#f9fafb"
 *   }}
 *   onResult={handleSuccess}
 *   onError={handleError}
 *   onAuth={handleAuth}
 * />
 * ```
 *
 * @example
 * With ref for artifact downloads:
 * ```tsx
 * const widgetRef = useRef<VanaAppUploadWidgetHandle>(null);
 * <VanaAppUploadWidget
 *   ref={widgetRef}
 *   appId="my-app-123"
 *   operation="prompt_gemini_agent"
 *   onResult={async (result) => {
 *     const artifact = result.artifacts?.[0];
 *     if (artifact && widgetRef.current) {
 *       const blob = await widgetRef.current.downloadArtifact({
 *         operationId: result.operationId,
 *         artifactPath: artifact.artifact_path
 *       });
 *     }
 *   }}
 *   onError={handleError}
 *   onAuth={handleAuth}
 * />
 * ```
 *
 * @param props - Configuration options for the widget
 * @param ref - Ref for accessing imperative methods like downloadArtifact
 * @returns A React component that renders the Vana data upload widget
 *
 * @public
 */
export const VanaAppUploadWidget = forwardRef<VanaAppUploadWidgetHandle, VanaAppUploadWidgetProps>(
  function VanaAppUploadWidget(
    {
      appId,
      onResult,
      onError,
      onAuth,
      onClose,
      iframeOrigin = "https://app.vana.com",
      schemaId,
      prompt,
      operation,
      operationParams,
      filters,
      theme,
      className = "w-full relative min-h-[550px]",
      style,
    },
    ref
  ) {
    const iframeRef = useRef<HTMLIFrameElement>(null);
    const iframeSrc = `${iframeOrigin}/embed/upload`;

    // Expose imperative handle for artifact downloads
    useImperativeHandle(
      ref,
      () => ({
        downloadArtifact: ({ operationId, artifactPath }) => {
          return new Promise<Blob>((resolve, reject) => {
            const iframe = iframeRef.current;
            if (!iframe?.contentWindow) {
              reject(new Error("Widget iframe not ready"));
              return;
            }

            const listener = (event: MessageEvent) => {
              // Verify origin for security
              if (event.origin !== iframeOrigin) {
                return;
              }

              // Match the response to this specific request
              if (
                event.data.operationId !== operationId ||
                event.data.artifactPath !== artifactPath
              ) {
                return;
              }

              // Handle success
              if (event.data.type === "ARTIFACT_CONTENT") {
                window.removeEventListener("message", listener);
                clearTimeout(timeoutId);
                resolve(event.data.content as Blob);
              }
              // Handle error
              else if (event.data.type === "ARTIFACT_ERROR") {
                window.removeEventListener("message", listener);
                clearTimeout(timeoutId);
                reject(new Error(event.data.error || "Failed to download artifact"));
              }
            };

            // Set up timeout (30 seconds)
            const timeoutId = setTimeout(() => {
              window.removeEventListener("message", listener);
              reject(new Error("Artifact download timeout after 30 seconds"));
            }, 30000);

            // Register listener
            window.addEventListener("message", listener);

            // Send download request to iframe
            iframe.contentWindow.postMessage(
              {
                type: "DOWNLOAD_ARTIFACT",
                operationId,
                artifactPath,
              },
              iframeOrigin
            );
          });
        },
      }),
      [iframeOrigin]
    );

    const handleMessage = useCallback(
      (event: MessageEvent) => {
        if (event.origin !== iframeOrigin) {
          return;
        }

        const { type, ...data } = event.data;

        switch (type) {
          case "ready": {
            if (iframeRef.current?.contentWindow) {
              iframeRef.current.contentWindow.postMessage(
                {
                  type: "config",
                  appId,
                  schemaId,
                  aiPrompt: prompt,
                  operation,
                  operationParams,
                  filters,
                  embeddingOrigin: window.location.origin,
                  theme,
                },
                iframeOrigin
              );
            }
            break;
          }

          case "relay": {
            if (iframeRef.current?.contentWindow && data.data) {
              iframeRef.current.contentWindow.postMessage(data.data, iframeOrigin);
            }
            break;
          }

          case "auth": {
            if (data.walletAddress) {
              onAuth(data.walletAddress);
            }
            break;
          }

          case "complete": {
            // event.data.result is the polling response with nested operation result
            const pollingResponse = data.result;

            if (pollingResponse?.status === "succeeded" && pollingResponse?.result) {
              const operationResult = pollingResponse.result;
              // Map SDK response to AgentOperationResult format
              const agentResult: AgentOperationResult = {
                output: operationResult.summary || operationResult.stdout,
                artifacts: operationResult.artifacts,
                operationId: pollingResponse.id,
              };
              onResult(agentResult);
            } else {
              // Handle cases where the operation might have failed or returned no result
              onError(pollingResponse?.error || "Operation completed with no result.");
            }
            break;
          }

          case "error": {
            const errorMessage = data.message || data.error || "An error occurred";
            onError(errorMessage);
            break;
          }

          case "resize": {
            if (data.height && iframeRef.current) {
              iframeRef.current.style.height = `${data.height}px`;
            }
            break;
          }

          case "close": {
            if (onClose) {
              onClose();
            }
            break;
          }

          case "ARTIFACT_CONTENT":
          case "ARTIFACT_ERROR": {
            // These messages are handled by the downloadArtifact() listener
            // No action needed here - just prevent unknown message warning
            break;
          }

          default: {
            if (process.env.NODE_ENV === "development") {
              console.warn(`[VanaAppUploadWidget] Unknown message type: ${type}`, data);
            }
          }
        }
      },
      [
        appId,
        schemaId,
        prompt,
        operation,
        operationParams,
        filters,
        theme,
        iframeOrigin,
        onAuth,
        onResult,
        onError,
        onClose,
      ]
    );

    useEffect(() => {
      window.addEventListener("message", handleMessage);
      return () => {
        window.removeEventListener("message", handleMessage);
      };
    }, [handleMessage]);

    return (
      <div className={className} style={style}>
        <iframe
          ref={iframeRef}
          src={iframeSrc}
          className="w-full border-none bg-transparent"
          style={{ width: "100%", border: "none", background: "transparent" }}
          sandbox="allow-same-origin allow-scripts allow-popups allow-popups-to-escape-sandbox"
          title="Vana Data Upload Widget"
        />
      </div>
    );
  }
);
